// Generated by scripts/prepare-photos.mjs from assets/puzzles/NNNN.jpg. Add images with `npm run photos:add`.
import type { ImageSourcePropType } from 'react-native';

/** Daily images, used in order and then repeated. All are 3:2. Credits: assets/puzzles/CREDITS.md. */
export const PUZZLE_IMAGES: ImageSourcePropType[] = [
  require('../assets/puzzles/0001.jpg'),
  require('../assets/puzzles/0002.jpg'),
  require('../assets/puzzles/0003.jpg'),
  require('../assets/puzzles/0004.jpg'),
  require('../assets/puzzles/0005.jpg'),
  require('../assets/puzzles/0006.jpg'),
  require('../assets/puzzles/0007.jpg'),
  require('../assets/puzzles/0008.jpg'),
];
